from .wdl_adult import wdl_adult
from .dcn_criteo import dcn_criteo
from .dc_criteo import dc_criteo
from .wdl_criteo import wdl_criteo
from .deepfm_criteo import dfm_criteo
from .wdl_avazu import wdl_avazu
from .deepfm_avazu import dfm_avazu
from .dcn_avazu import dcn_avazu
from .dfmslr_avazu import dfmslr_avazu
from .dfmsfm_criteosearch import dfmsfm_criteosearch
from .ncf_movie import ncf_movie
from .deepfm_criteosearch import dfm_criteosearch
from .dcn_criteosearch import dcn_criteosearch