from .wdl_adult import wdl_adult
from .dcn_criteo import dcn_criteo
from .dc_criteo import dc_criteo
from .wdl_criteo import wdl_criteo
from .deepfm_criteo import dfm_criteo
from .wdl_avazu import wdl_avazu
from .deepfm_avazu import dfm_avazu
from .dcn_avazu import dcn_avazu
from .dfmslr_avazu import dfmslr_avazu
from .dfmsfm_criteosearch import dfmsfm_criteosearch
from .ncf_movie import ncf_movie
from .deepfm_criteosearch import dfm_criteosearch
from .dcn_criteosearch import dcn_criteosearch
from .fae_wdl_criteo import fae_wdl_criteo
from .fae_deepfm_avazu import fae_dfm_avazu
from .fae_dcn_criteosearch import fae_dcn_criteosearch
from .fae_ncf_movie import fae_ncf_movie
from .emb_sum_wdl_criteo import emb_sum_wdl_criteo
from .emb_sum_deepfm_avazu import emb_sum_dfm_avazu
from .emb_sum_dcn_criteosearch import emb_sum_dcn_criteosearch
from .emb_sum_ncf_movie import emb_sum_ncf_movie